// Strings of the BM tab (js/bms.js). Plain data + one addStrings call, so test/pure.test.mjs can load it in Node and check
// that every key used anywhere exists in both languages. Keys: "bms.<what>"; the generic ones (copied, ago.*, err.*,
// acc.copyId / acc.idCopied) come from the main dictionary.
import { addStrings } from "../i18n.js";

export const STRINGS = {
  ru: {
    "bms.search.aria": "Поиск по BM",
    "bms.copyIds": "ID BM", "bms.copyIds.title": "ID показанных BM списком, по одному в строке",
    "bms.refresh": "Обновить BM",
    "bms.total": "{n} BM", "bms.found": "найдено {n} из {all}", "bms.notAll": " (не все)", "bms.updated": "обновлено {t}",
    "bms.loaded": "BM: {n}", "bms.truncated": " (не все — лимит 4 страницы)", "bms.partial": " (список неполный)",
    "bms.idsCopied": "Скопировано ID: {n}", "bms.wait": "Обновить можно через {n} с",
    "bms.empty": "BM не загружены — нажми кнопку обновления сверху", "bms.loading": "Загрузка BM…",
    "bms.none": "На этом профиле нет BM", "bms.noMatch": "Ничего не найдено",
    "bms.noPerm": "Этот токен не читает BM. Открой вкладку Business Manager или Ads Manager, обнови токен (⟳ на вкладке «Токен») и нажми обновить.",
    "bms.noName": "Без названия", "bms.noField": "Graph не отдал это поле для этого токена",
    "bms.verTitle": "Верификация бизнеса",
    "bms.ver.verified": "Подтверждён", "bms.ver.pending": "На проверке", "bms.ver.pending_need_more_info": "Нужны данные",
    "bms.ver.pending_submission": "Ждёт отправки", "bms.ver.failed": "Не прошёл", "bms.ver.rejected": "Отклонён",
    "bms.ver.revoked": "Отозван", "bms.ver.expired": "Истёк срок", "bms.ver.not_verified": "Не подтверждён", "bms.ver.ineligible": "Недоступно",
    "bms.roleTitle": "Твоя роль в этом BM", "bms.role.admin": "Админ", "bms.role.employee": "Сотрудник",
    "bms.created": "Создан {d}", "bms.createdTitle": "Дата создания BM",
    "bms.page": "Страница: {n}", "bms.pageTitle": "Основная страница BM · {id}",
    "bms.tfa": "2FA: {v}", "bms.tfaTitle": "Какой двухфакторки требует этот BM",
    "bms.tfa.none": "не требуется", "bms.tfa.admin_required": "для админов", "bms.tfa.all_required": "для всех",
    "bms.accCount": ["кабинет", "кабинета", "кабинетов"], "bms.accActive": " · {n} активно", "bms.accDisabled": " · {n} заблокировано",
    "bms.accsTitle": "Показать эти кабинеты на вкладке «Кабинеты»", "bms.accsPartial": "Список кабинетов загружен не полностью — их может быть больше",
    "bms.accsNone": "Нет кабинетов", "bms.accsNoneTitle": "Среди загруженных на вкладке «Кабинеты» нет кабинетов этого BM",
    "bms.accsShow": "Показать кабинеты", "bms.accsShowTitle": "Открыть вкладку «Кабинеты» с фильтром по этому BM (список загрузится сам)",
    "bms.link.settings": "Настройки", "bms.link.settings.title": "Настройки этого BM в Business Settings",
    "bms.link.accounts": "Кабинеты", "bms.link.accounts.title": "Рекламные кабинеты этого BM в Business Settings",
    "bms.link.security": "Верификация", "bms.link.security.title": "Безопасность BM: верификация бизнеса и 2FA",
    "bms.link.quality": "Качество", "bms.link.quality.title": "Business Support Home: ограничения и апелляции этого BM",
  },
  en: {
    "bms.search.aria": "Search business managers",
    "bms.copyIds": "Copy IDs", "bms.copyIds.title": "IDs of the shown business managers, one per line",
    "bms.refresh": "Refresh business managers",
    "bms.total": "{n} BM", "bms.found": "{n} of {all} found", "bms.notAll": " (not all)", "bms.updated": "updated {t}",
    "bms.loaded": "Business managers: {n}", "bms.truncated": " (not all — 4-page limit)", "bms.partial": " (list incomplete)",
    "bms.idsCopied": "Copied IDs: {n}", "bms.wait": "Refresh available in {n} s",
    "bms.empty": "Business managers not loaded — press the refresh button above", "bms.loading": "Loading business managers…",
    "bms.none": "No business managers on this profile", "bms.noMatch": "Nothing found",
    "bms.noPerm": "This token can't read business managers. Open a Business Manager or Ads Manager tab, refresh the token (⟳ on the Token tab) and press refresh.",
    "bms.noName": "No name", "bms.noField": "Graph did not return this field for this token",
    "bms.verTitle": "Business verification",
    "bms.ver.verified": "Verified", "bms.ver.pending": "Pending", "bms.ver.pending_need_more_info": "Needs more info",
    "bms.ver.pending_submission": "Pending submission", "bms.ver.failed": "Failed", "bms.ver.rejected": "Rejected",
    "bms.ver.revoked": "Revoked", "bms.ver.expired": "Expired", "bms.ver.not_verified": "Not verified", "bms.ver.ineligible": "Ineligible",
    "bms.roleTitle": "Your role in this business", "bms.role.admin": "Admin", "bms.role.employee": "Employee",
    "bms.created": "Created {d}", "bms.createdTitle": "When the business was created",
    "bms.page": "Page: {n}", "bms.pageTitle": "Primary page of the business · {id}",
    "bms.tfa": "2FA: {v}", "bms.tfaTitle": "Two-factor authentication this business requires",
    "bms.tfa.none": "not required", "bms.tfa.admin_required": "admins", "bms.tfa.all_required": "everyone",
    "bms.accCount": ["ad account", "ad accounts"], "bms.accActive": " · {n} active", "bms.accDisabled": " · {n} disabled",
    "bms.accsTitle": "Show these ad accounts in the Ad accounts tab", "bms.accsPartial": "The ad account list is not complete — there may be more",
    "bms.accsNone": "No ad accounts", "bms.accsNoneTitle": "None of the ad accounts loaded in the Ad accounts tab belongs to this business",
    "bms.accsShow": "Show ad accounts", "bms.accsShowTitle": "Open the Ad accounts tab filtered by this business (the list loads by itself)",
    "bms.link.settings": "Settings", "bms.link.settings.title": "This business in Business Settings",
    "bms.link.accounts": "Ad accounts", "bms.link.accounts.title": "Ad accounts of this business in Business Settings",
    "bms.link.security": "Verification", "bms.link.security.title": "Business security: verification and 2FA",
    "bms.link.quality": "Quality", "bms.link.quality.title": "Business Support Home: restrictions and appeals of this business",
  },
};
addStrings(STRINGS);
