// Strings of the Businesses tab (js/bms.js). Plain data + one addStrings call, so test/pure.test.mjs can load it in Node and check
// that every key used anywhere exists in both languages. Keys: "bms.<what>"; the generic ones (copied, ago.*, err.*, search,
// acc.copyId / acc.idCopied / acc.spend / acc.refreshDash, period.*) come from the main dictionary.
// Wording: "бизнес-портфолио" / "business portfolio" is Meta's name for the thing; where a short word is needed (tab, counts,
// buttons) it is "бизнесы" / "businesses". "BM" / "БМ" is slang and is not used in the interface.
import { addStrings } from "../i18n.js";

export const STRINGS = {
  ru: {
    "bms.search.aria": "Поиск бизнесов",
    "bms.copyIds": "ID бизнесов", "bms.copyIds.title": "ID показанных бизнесов списком, по одному в строке",
    "bms.refresh": "Обновить бизнесы и спенд",
    "bms.count": ["бизнес", "бизнеса", "бизнесов"], "bms.found": "найдено {n} из {all}", "bms.notAll": " (не все)", "bms.updated": "обновлено {t}",
    "bms.loaded": "Бизнесов: {n}", "bms.truncated": " (не все — лимит 4 страницы)", "bms.partial": " (список неполный)",
    "bms.idsCopied": "Скопировано ID: {n}", "bms.wait": "Обновить можно через {n} с",
    "bms.empty": "Бизнесы не загружены — нажми кнопку обновления сверху", "bms.loading": "Загрузка бизнесов…",
    "bms.none": "На этом профиле нет бизнес-портфолио", "bms.noMatch": "Ничего не найдено",
    "bms.noPerm": "Этот токен не читает бизнес-портфолио. Открой вкладку Business Manager или Ads Manager, обнови токен (⟳ на вкладке «Токен») и нажми обновить.",
    "bms.noName": "Без названия", "bms.noSpend": "Спенд берётся из списка кабинетов — он ещё не загружен",
    "bms.spend": "Спенд бизнесов",
    "bms.openSettings": "Открыть этот бизнес в Business Settings",
    "bms.st.active": "Активен", "bms.st.active.title": "В этом бизнесе есть хотя бы один активный рекламный кабинет",
    "bms.st.noActive": "Нет активных кабинетов", "bms.st.noActive.title": "В этом бизнесе есть кабинеты, но ни один не активен (статус Active)",
    "bms.st.none": "Нет кабинетов", "bms.st.none.title": "Среди загруженных на вкладке «Кабинеты» нет кабинетов этого бизнеса",
    "bms.verTitle": "Верификация бизнеса",
    "bms.p.ver.failed": "Верификация не пройдена", "bms.p.ver.rejected": "Верификация отклонена",
    "bms.p.ver.revoked": "Верификация отозвана", "bms.p.ver.expired": "Верификация истекла",
    "bms.fix.verify": "Открыть верификацию", "bms.fix.verifyTitle": "Business Settings → Безопасность: верификация этого бизнеса",
    "bms.fix.accounts": "Кабинеты", "bms.fix.accountsTitle": "Рекламные кабинеты этого бизнеса в Business Settings",
    "bms.fix.create": "Создать кабинет", "bms.fix.createTitle": "Business Settings → Рекламные кабинеты → Добавить: создай рекламный кабинет в этом бизнесе",
    "bms.accCount": ["кабинет", "кабинета", "кабинетов"], "bms.accActive": " · {n} активно", "bms.accDisabled": " · {n} заблокировано",
    "bms.accsTitle": "Показать эти кабинеты на вкладке «Кабинеты»", "bms.accsPartial": "Список кабинетов загружен не полностью — их может быть больше",
    "bms.accsShow": "Показать кабинеты", "bms.accsShowTitle": "Открыть вкладку «Кабинеты» с фильтром по этому бизнесу (список загрузится сам)",
  },
  en: {
    "bms.search.aria": "Search businesses",
    "bms.copyIds": "Copy IDs", "bms.copyIds.title": "IDs of the shown businesses, one per line",
    "bms.refresh": "Refresh businesses and spend",
    "bms.count": ["business", "businesses"], "bms.found": "{n} of {all} found", "bms.notAll": " (not all)", "bms.updated": "updated {t}",
    "bms.loaded": "Businesses: {n}", "bms.truncated": " (not all — 4-page limit)", "bms.partial": " (list incomplete)",
    "bms.idsCopied": "Copied IDs: {n}", "bms.wait": "Refresh available in {n} s",
    "bms.empty": "Businesses not loaded — press the refresh button above", "bms.loading": "Loading businesses…",
    "bms.none": "No business portfolios on this profile", "bms.noMatch": "Nothing found",
    "bms.noPerm": "This token can't read business portfolios. Open a Business Manager or Ads Manager tab, refresh the token (⟳ on the Token tab) and press refresh.",
    "bms.noName": "No name", "bms.noSpend": "Spend comes from the Ad accounts list, which is not loaded yet",
    "bms.spend": "Spend of businesses",
    "bms.openSettings": "Open this business in Business Settings",
    "bms.st.active": "Active", "bms.st.active.title": "This business has at least one active ad account",
    "bms.st.noActive": "No active ad accounts", "bms.st.noActive.title": "This business has ad accounts, but none is active (status Active)",
    "bms.st.none": "No ad accounts", "bms.st.none.title": "None of the ad accounts loaded in the Ad accounts tab belongs to this business",
    "bms.verTitle": "Business verification",
    "bms.p.ver.failed": "Verification failed", "bms.p.ver.rejected": "Verification rejected",
    "bms.p.ver.revoked": "Verification revoked", "bms.p.ver.expired": "Verification expired",
    "bms.fix.verify": "Open verification", "bms.fix.verifyTitle": "Business Settings → Security: verification of this business",
    "bms.fix.accounts": "Ad accounts", "bms.fix.accountsTitle": "Ad accounts of this business in Business Settings",
    "bms.fix.create": "Create ad account", "bms.fix.createTitle": "Business Settings → Ad accounts → Add: create an ad account in this business",
    "bms.accCount": ["ad account", "ad accounts"], "bms.accActive": " · {n} active", "bms.accDisabled": " · {n} disabled",
    "bms.accsTitle": "Show these ad accounts in the Ad accounts tab", "bms.accsPartial": "The ad account list is not complete — there may be more",
    "bms.accsShow": "Show ad accounts", "bms.accsShowTitle": "Open the Ad accounts tab filtered by this business (the list loads by itself)",
  },
};
addStrings(STRINGS);
